import os
from typing import List, Dict, Any
import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

class NightwatchGenerator:
    def __init__(self, output_dir: str = "generated_tests/nightwatch"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.template = """module.exports = {{\n  '@tags': ['e2e', 'generated'],\n  '{test_name}': function (browser) {{\n    const testData = {test_data};\n    \n    browser\n      .url(browser.launch_url)\n      .waitForElementVisible('body')\n      {test_steps}\n      .end();\n  }}\n}};"""
        self.step_templates = {
            "click": ".click('{selector}')",
            "type": ".setValue('{selector}', '{value}')",
            "assert": ".assert.visible('{selector}')",
            "wait": ".waitForElementVisible('{selector}', {timeout})",
            "navigate": ".url('{url}')"
        }

    def generate_test_case(self, test_case: Dict[str, Any]) -> str:
        """Generate Nightwatch.js test case from test case dictionary."""
        test_steps = []
        
        for step in test_case.get("steps", []):
            step_type = step.get("action_type", "click")
            template = self.step_templates.get(step_type, "")
            
            if step_type == "type":
                test_steps.append(template.format(
                    selector=step.get("selector", ""),
                    value=step.get("value", "")
                ))
            elif step_type == "wait":
                test_steps.append(template.format(
                    selector=step.get("selector", "body"),
                    timeout=step.get("timeout", 5000)
                ))
            elif step_type == "navigate":
                test_steps.append(template.format(
                    url=step.get("url", "browser.launch_url")
                ))
            else:
                test_steps.append(template.format(
                    selector=step.get("selector", "body")
                ))
        
        return self.template.format(
            test_name=test_case.get("name", "GeneratedTest").replace(" ", ""),
            test_steps="\n      ".join(test_steps),
            test_data=json.dumps(test_case.get("test_data", {}), indent=2)
        )

    def save_test_file(self, test_cases: List[Dict[str, Any]], filename: str = "generated_test.js"):
        """Save generated test cases to a file."""
        test_content = "\n\n".join(
            self.generate_test_case(tc) for tc in test_cases
        )
        
        output_path = self.output_dir / filename
        with open(output_path, "w") as f:
            f.write("// Auto-generated by Prism Test Automation Framework\n")
            f.write("// " + "="*70 + "\n\n")
            f.write(test_content)
        
        logger.info(f"Saved Nightwatch.js test to {output_path}")
        return str(output_path)
