const axios = require('axios');

/**
 * Pushes validated AI-generated test cases to Zephyr Scale Cloud.
 * @param {Object} validatedJson - The JSON output from your Validator.
 */
async function pushToZephyr(validatedJson) {
  const url = 'https://api.zephyrscale.smartbear.com/v2/testcases';
  
  const headers = {
    'Authorization': `Bearer ${process.env.ZEPHYR_API_TOKEN}`,
    'Content-Type': 'application/json'
  };

  // Loop through each test case generated by Gemini
  for (const testCase of validatedJson.cases) {
    const payload = {
      projectKey: "ZT", // Replace with your actual Project Key (e.g., SHOP)
      name: testCase.title,
      objective: `AI-Generated Test Case for Jira Story ${validatedJson.source_issue}`,
      statusName: "Draft",
      priorityName: "Normal",
      testScript: {
        type: "STEP_BY_STEP",
        steps: testCase.steps.map(step => ({
          description: step.action,
          expectedResult: step.expected
        }))
      }
    };

    try {
      const response = await axios.post(url, payload, { headers });
      console.log(`✅ Created Zephyr Test Case: ${response.data.key} - ${testCase.title}`);
    } catch (error) {
      console.error(`❌ Failed to push ${testCase.title}:`, error.response ? error.response.data : error.message);
    }
  }
}

module.exports = { pushToZephyr };
